dist: trusty
sudo: false
language: python
python:
- "2.7"
- "3.4"
- "3.5"
- "3.6"
install:
- pip install codecov tox-travis
- virtualenv --version
- easy_install --version
- pip --version
- tox --version
script:
- tox -v
after_success:
- codecov
